site_name: RP Tech Documentation
site_url: https://techdocs.reformedperspective.ca

theme:
  name: mkdocs
  nav_style: light

nav:
  - Home: index.md
  - Website:
    - About: website/index.md
    - Wordpress: website/wordpress.md
    - Benchpress: website/benchpress.md
    - PHP: website/php.md
    - Git: website/git.md
    - Dreamhost: website/dreamhost.md
    - Cloudflare: website/cloudflare.md
  - Google: google.md
  - Manna: manna.md
  - App: app.md
  - Procedures: procedures.md